def get_args_config():
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('--host', default=config['host'], help='The host the server will bind to. Use 0.0.0.0 for all interfaces.')
    parser.add_argument('--port', type=int, default=config['port'], help='The port the server will bind to.')
    parser.add_argument('--width', type=int, default=config['width'], help='Number of elements used from left to right.')
    parser.add_argument('--height', type=int, default=config['height'], help='Number of elements used from top to bottom.')
    parser.add_argument('--blur', type=int, default=config['blur'], help='Pixels used in the gaussian blur.')
    parser.add_argument('--no-censor', action='store_true', help='Disables gaussian blur.')
    parser.add_argument('--no-colors', action='store_true', help='Disables hue rotation.')
    return vars(parser.parse_args())