def run_main():
    window = aui_manager.GetManagedWindow()
    if 'SCT_DIR' not in os.environ:
        dlg = wx.MessageDialog(window, 'Spinal Cord Toolbox (SCT) was not found in your system. Make sure you open fsleyes from the Terminal (not by clicking on the App). If you are indeed running from the Terminal, please check the installation procedure at: https://github.com/neuropoly/spinalcordtoolbox', 'SCT not found!', wx.OK | wx.ICON_INFORMATION)
        dlg.ShowModal()
        dlg.Destroy()
        return
    notebook = aui.AuiNotebook(parent=window)
    panel_propseg = TabPanelPropSeg(parent=notebook)
    panel_sc = TabPanelSCSeg(parent=notebook)
    panel_gm = TabPanelGMSeg(parent=notebook)
    panel_vlb = TabPanelVertLB(parent=notebook)
    panel_reg = TabPanelRegisterToTemplate(parent=notebook)
    notebook.AddPage(page=panel_propseg, caption='sct_propseg', select=True)
    notebook.AddPage(page=panel_sc, caption='sct_deepseg_sc', select=False)
    notebook.AddPage(page=panel_gm, caption='sct_deepseg_gm', select=False)
    notebook.AddPage(page=panel_vlb, caption='sct_label_vertebrae', select=False)
    notebook.AddPage(page=panel_reg, caption='sct_register_to_template', select=False)
    aui_manager.AddPane(notebook, aui.AuiPaneInfo().Name('notebook_content').CenterPane().PaneBorder(False))
    aui_manager.Update()