async def main():
    print('in main ')
    print(os.environ.get('PYPPETEER_CHROMIUM_REVISION'))
    browser = await pyppeteer.launch(executablePath='D:\\A\\Desktop\\项目+更新\\node_project\\chrome-win\\chrome-win\\chrome.exe', headless=False, args=['--proxy-server=118.24.156.214:8118'], timeout=30000)
    page = await browser.newPage()
    await page.setViewport({'width': 1000, 'height': 780})
    await page.setUserAgent('Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36')
    await page.goto('http://httpbin.net/ip')
    content = await page.content()
    cookies = await page.cookies()
    await page.screenshot({'path': 'example.png'})
    dimensions = await page.evaluate('() => {\n        return {\n            width: document.documentElement.clientWidth,\n            height: document.documentElement.clientHeight,\n            deviceScaleFactor: window.devicePixelRatio,\n        }\n    }')
    print(dimensions)
    await browser.close()
    return {'content': content, 'cookies': cookies}