def main():
    p = optparse.OptionParser()
    p.add_option('-o', '--output', help='location of generated file')
    p.add_option('-p', '--protos', help='A file with all ' + 'prototypes to generate Python wrappers for, one per line. Generate it with docs/scripts/checkdocs.py -p')
    p.add_option('-t', '--type', help='the library type to ' + 'use, e.g. debug')
    p.add_option('-v', '--version', help='the library version to ' + 'use, e.g. 5.1')
    options, args = p.parse_args()
    if not options.protos:
        p.print_help()
        return
    al = Allegro()
    al.parse_protos(options.protos)
    f = open(options.output, 'w') if options.output else sys.stdout
    release = options.type
    version = options.version
    f.write('# Generated by generate_python_ctypes.py.\nimport os, platform, sys\nfrom ctypes import *\nfrom ctypes.util import *\n\n# You must adjust this function to point ctypes to the A5 DLLs you are\n# distributing.\n_dlls = []\ndef _add_dll(name):\n    release = "%(release)s"\n    if os.name == "nt":\n        release = "%(release)s-%(version)s"\n\n    # Under Windows, DLLs are found in the current directory, so this\n    # would be an easy way to keep all your DLLs in a sub-folder.\n\n    # os.chdir("dlls")\n\n    path = find_library(name + release)\n    if not path:\n        if os.name == "mac":\n            path = name + release + ".dylib"\n        elif os.name == "nt":\n            path = name + release + ".dll"\n        elif os.name == "posix":\n            if platform.mac_ver()[0]:\n                path = name + release + ".dylib"\n            else:\n                path = "lib" + name + release + ".so"\n        else:\n            sys.stderr.write("Cannot find library " + name + "\\n")\n\n        # In most cases, you actually don\'t want the above and instead\n        # use the exact filename within your game distribution, possibly\n        # even within a .zip file.\n        # if not os.path.exists(path):\n        #     path = "dlls/" + path\n\n    try:\n        # RTLD_GLOBAL is required under OSX for some reason (?)\n        _dlls.append(CDLL(path, RTLD_GLOBAL))\n    except OSError:\n        # No need to fail here, might just be one of the addons.\n        pass\n\n    # os.chdir("..")\n\n_add_dll("allegro")\n_add_dll("allegro_acodec")\n_add_dll("allegro_audio")\n_add_dll("allegro_primitives")\n_add_dll("allegro_color")\n_add_dll("allegro_font")\n_add_dll("allegro_ttf")\n_add_dll("allegro_image")\n_add_dll("allegro_dialog")\n_add_dll("allegro_memfile")\n_add_dll("allegro_physfs")\n_add_dll("allegro_shader")\n_add_dll("allegro_main")\n_add_dll("allegro_monolith")\n\n# We don\'t have information ready which A5 function is in which DLL,\n# so we just try them all.\ndef _dll(func, ret, params):\n    for dll in _dlls:\n        try:\n            f = dll[func]\n            f.restype = ret\n            f.argtypes = params\n            return f\n        except AttributeError: pass\n    sys.stderr.write("Cannot find function " + func + "\\n")\n    return lambda *args: None\n\n# In Python3, all Python strings are unicode so we have to convert to\n# UTF8 byte strings before passing to Allegro.\nif sys.version_info[0] > 2:\n    class _AL_UTF8String:\n        def from_param(x):\n            return x.encode("utf8")\nelse:\n    _AL_UTF8String = c_char_p\n\n' % locals())
    postpone = []
    for name, val in sorted(al.constants.items()):
        try:
            if isinstance(val, str):
                val = int(eval(val, globals(), al.constants))
            f.write(name + ' = ' + str(val) + '\n')
        except:
            postpone.append((name, val))
    for name, val in postpone:
        f.write(name + ' = ' + val + '\n')
    structs = set()
    for name, x in sorted(al.types.items()):
        if not name:
            continue
        base = x.__bases__[0]
        if base != Structure and base != Union:
            f.write(name + ' = ' + x.__name__ + '\n')
        else:
            structs.add(name)
    structs_list = []
    remaining = set(structs)
    while remaining:
        for name in sorted(remaining):
            ok = True
            x = al.types[name]
            if hasattr(x, 'my_fields'):
                for fname, ftype in x.my_fields:
                    if ' ' in ftype:
                        ftype = ftype.split()[0]
                    if ftype in structs and ftype in remaining:
                        ok = False
                        break
            if ok:
                structs_list.append(name)
                remaining.remove(name)
    for name in structs_list:
        x = al.types[name]
        base = x.__bases__[0]
        f.write('class ' + name + '(' + base.__name__ + '):\n')
        if hasattr(x, 'my_fields'):
            f.write('    _fields_ = [\n')
            for fname, ftype in x.my_fields:
                f.write('    ("' + fname + '", ' + ftype + '),\n')
            f.write('    ]\n')
        else:
            f.write('    pass\n')
        pt = POINTER(x)
        f.write('%s = POINTER(%s)\n' % (pt.__name__, name))
    for name, x in sorted(al.functions.items()):
        try:
            line = name + ' = _dll("' + name + '", '
            line += x.restype.__name__ + ', '
            line += '[' + ', '.join([a.__name__ for a in x.argtypes]) + '])\n'
            f.write(line)
        except AttributeError as e:
            print('Ignoring ' + name + ' because of errors (' + str(e) + ').')
    f.write('\nALLEGRO_VERSION_INT = \\\n    ((ALLEGRO_VERSION << 24) | (ALLEGRO_SUB_VERSION << 16) | \\\n    (ALLEGRO_WIP_VERSION << 8) | ALLEGRO_RELEASE_NUMBER)\n    ')
    f.write('\n# work around bug http://gcc.gnu.org/bugzilla/show_bug.cgi?id=36834\nif os.name == "nt":\n    def al_map_rgba_f(r, g, b, a): return ALLEGRO_COLOR(r, g, b, a)\n    def al_map_rgb_f(r, g, b): return ALLEGRO_COLOR(r, g, b, 1)\n    def al_map_rgba(r, g, b, a):\n        return ALLEGRO_COLOR(r / 255.0, g / 255.0, b / 255.0, a / 255.0)\n    def al_map_rgb(r, g, b):\n        return ALLEGRO_COLOR(r / 255.0, g / 255.0, b / 255.0, 1)\n    ')
    f.write('\ndef al_main(real_main, *args):\n    def python_callback(argc, argv):\n        real_main(*args)\n        return 0\n    cb = CFUNCTYPE(c_int, c_int, c_void_p)(python_callback)\n    al_run_main(0, 0, cb);\n')
    f.close()