@pytest.fixture()
def setup_scopez_server_action():
    l_file_path = os.path.dirname(os.path.abspath(__file__))
    l_geoip2city_path = os.path.realpath(os.path.join(l_file_path, '../../data/waf/db/GeoLite2-City.mmdb'))
    l_geoip2ISP_path = os.path.realpath(os.path.join(l_file_path, '../../data/waf/db/GeoLite2-ASN.mmdb'))
    l_conf_dir = os.path.realpath(os.path.join(l_file_path, '../../data/waf/conf'))
    l_ruleset_path = os.path.realpath(os.path.join(l_file_path, '../../data/waf/ruleset'))
    l_scopez_dir = os.path.realpath(os.path.join(l_file_path, '../../data/waf/conf/scopes'))
    l_an_list = os.path.realpath(os.path.join(l_file_path, '../../data/an/an-scopes.json'))
    l_scopez_server_path = os.path.abspath(os.path.join(l_file_path, '../../../build/util/scopez_server/scopez_server'))
    l_bot_challenge = os.path.realpath(os.path.join(l_file_path, '../../data/bot/bot-challenges.json'))
    l_subproc = subprocess.Popen([l_scopez_server_path, '-d', l_conf_dir, '-S', l_scopez_dir, '-l', l_an_list, '-r', l_ruleset_path, '-g', l_geoip2city_path, '-i', l_geoip2ISP_path, '-c', l_bot_challenge, '-a'])
    print('cmd: {}'.format(' '.join([l_scopez_server_path, '-d', l_conf_dir, '-S', l_scopez_dir, '-l', l_an_list, '-r', l_ruleset_path, '-g', l_geoip2city_path, '-i', l_geoip2ISP_path, '-c', l_bot_challenge, '-a'])))
    time.sleep(1)
    yield setup_scopez_server_action
    _, _, _ = run_command('kill -9 %d' % l_subproc.pid)
    time.sleep(0.5)