def test_Pow():
    assert str(x ** (-1)) == '1/x'
    assert str(x ** (-2)) == 'x**(-2)'
    assert str(x ** 2) == 'x**2'
    assert str((x + y) ** (-1)) == '1/(x + y)'
    assert str((x + y) ** (-2)) == '(x + y)**(-2)'
    assert str((x + y) ** 2) == '(x + y)**2'
    assert str((x + y) ** (1 + x)) == '(x + y)**(x + 1)'
    assert str(x ** Rational(1, 3)) == 'x**(1/3)'
    assert str(1 / x ** Rational(1, 3)) == 'x**(-1/3)'
    assert str(sqrt(sqrt(x))) == 'x**(1/4)'
    assert str(x ** (-1.0)) == '1/x'