def pytest_addoption(parser):
    parser.addoption('--build-image', '-D', action='store_true')
    parser.addoption('--build-base-image', '-B', action='store_true')
    parser.addoption('--aws-id')
    parser.addoption('--instance-type')
    parser.addoption('--accelerator-type', default=None)
    parser.addoption('--docker-base-name', default='pytorch')
    parser.addoption('--region', default='us-west-2')
    parser.addoption('--framework-version', default=PyTorch.LATEST_VERSION)
    parser.addoption('--py-version', choices=['2', '3'], default=str(sys.version_info.major))
    parser.addoption('--processor', choices=['gpu', 'cpu', 'eia'], default='cpu')
    parser.addoption('--tag', default=None)
    parser.addoption('--generate-coverage-doc', default=False, action='store_true', help='use this option to generate test coverage doc')