def main(args):
    logger, env_info, model_kwargs = lfna_setup(args)
    to_evaluate_indexes = split_str2indexes(args.srange, env_info['total'], None)
    logger.log('Evaluate {:}, which has {:} timestamps in total.'.format(args.srange, len(to_evaluate_indexes)))
    w_container_per_epoch = dict()
    per_timestamp_time, start_time = (AverageMeter(), time.time())
    for i, idx in enumerate(to_evaluate_indexes):
        need_time = 'Time Left: {:}'.format(convert_secs2time(per_timestamp_time.avg * (len(to_evaluate_indexes) - i), True))
        logger.log('[{:}]'.format(time_string()) + ' [{:04d}/{:04d}][{:04d}]'.format(i, len(to_evaluate_indexes), idx) + ' ' + need_time)
        historical_x = env_info['{:}-x'.format(idx)]
        historical_y = env_info['{:}-y'.format(idx)]
        model = get_model(dict(model_type='simple_mlp'), **model_kwargs)
        optimizer = torch.optim.Adam(model.parameters(), lr=args.init_lr, amsgrad=True)
        criterion = torch.nn.MSELoss()
        lr_scheduler = torch.optim.lr_scheduler.MultiStepLR(optimizer, milestones=[int(args.epochs * 0.25), int(args.epochs * 0.5), int(args.epochs * 0.75)], gamma=0.3)
        train_metric = MSEMetric()
        best_loss, best_param = (None, None)
        for _iepoch in range(args.epochs):
            preds = model(historical_x)
            optimizer.zero_grad()
            loss = criterion(preds, historical_y)
            loss.backward()
            optimizer.step()
            lr_scheduler.step()
            if best_loss is None or best_loss > loss.item():
                best_loss = loss.item()
                best_param = copy.deepcopy(model.state_dict())
        model.load_state_dict(best_param)
        with torch.no_grad():
            train_metric(preds, historical_y)
        train_results = train_metric.get_info()
        metric = ComposeMetric(MSEMetric(), SaveMetric())
        eval_dataset = torch.utils.data.TensorDataset(env_info['{:}-x'.format(idx)], env_info['{:}-y'.format(idx)])
        eval_loader = torch.utils.data.DataLoader(eval_dataset, batch_size=args.batch_size, shuffle=False, num_workers=0)
        results = basic_eval_fn(eval_loader, model, metric, logger)
        log_str = '[{:}]'.format(time_string()) + ' [{:04d}/{:04d}]'.format(idx, env_info['total']) + ' train-mse: {:.5f}, eval-mse: {:.5f}'.format(train_results['mse'], results['mse'])
        logger.log(log_str)
        save_path = logger.path(None) / '{:04d}-{:04d}.pth'.format(idx, env_info['total'])
        w_container_per_epoch[idx] = model.get_w_container().no_grad_clone()
        save_checkpoint({'model_state_dict': model.state_dict(), 'model': model, 'index': idx, 'timestamp': env_info['{:}-timestamp'.format(idx)]}, save_path, logger)
        logger.log('')
        per_timestamp_time.update(time.time() - start_time)
        start_time = time.time()
    save_checkpoint({'w_container_per_epoch': w_container_per_epoch}, logger.path(None) / 'final-ckp.pth', logger)
    logger.log('-' * 200 + '\n')
    logger.close()