def buildModel():
    model = Sequential()
    layer1 = Conv2D(L1, FILTER_SIZE_1, activation='relu', input_shape=INPUT_SHAPE, kernel_initializer='uniform')
    model.add(layer1)
    model.add(MaxPooling2D(pool_size=POOLING_SIZE))
    layer2 = Conv2D(L2, FILTER_SIZE_2, activation='relu', kernel_initializer='uniform')
    model.add(layer2)
    model.add(MaxPooling2D(pool_size=POOLING_SIZE))
    model.add(Flatten())
    layer3 = Dense(L3, activation='relu', kernel_initializer='uniform')
    model.add(layer3)
    layer4 = Dense(L4, activation='softmax', kernel_initializer='uniform')
    model.add(layer4)
    adam = Adam(lr=0.01)
    model.compile(loss='mean_squared_error', optimizer=adam)
    weights = model.get_weights()
    print(len(weights))
    print('====================================')
    return model