def save4image(lh_sphere_sub, lh_sphere_atlas, lh_sulc_sub, lh_sulc_atlas, lh_sphere_freesurfer, phi_prime, theta_prime, imagesavefilename):
    lh_morph_sulc_sub = nib.freesurfer.read_morph_data(lh_sulc_sub)
    lh_morph_sulc_atlas = nib.freesurfer.read_morph_data(lh_sulc_atlas)
    coords_sub, faces_sub = nib.freesurfer.read_geometry(lh_sphere_sub)
    r_sub, phi_sub, theta_sub = cartesian_to_spherical(coords_sub[:, 0], coords_sub[:, 1], coords_sub[:, 2])
    coords_atlas, faces_atlas = nib.freesurfer.read_geometry(lh_sphere_atlas)
    r_atlas, phi_atlas, theta_atlas = cartesian_to_spherical(coords_atlas[:, 0], coords_atlas[:, 1], coords_atlas[:, 2])
    coords_freesurfer, faces_freesurfer = nib.freesurfer.read_geometry(lh_sphere_freesurfer)
    r_reg, phi_reg, theta_reg = cartesian_to_spherical(coords_freesurfer[:, 0], coords_freesurfer[:, 1], coords_freesurfer[:, 2])
    fig = plt.figure(figsize=(14, 7))
    ax = fig.add_subplot(141)
    ax.scatter(phi_sub.degree, theta_sub.degree, s=0.1, c=lh_morph_sulc_sub)
    plt.title('Moving')
    ax = fig.add_subplot(142)
    ax.scatter(phi_atlas.degree, theta_atlas.degree, s=0.1, c=lh_morph_sulc_atlas)
    plt.title('Fixed')
    ax = fig.add_subplot(143)
    phi_prime = [math.degrees(p) for p in phi_prime]
    thtea_prime = [math.degrees(t) for t in theta_prime]
    ax.scatter(phi_prime, thtea_prime, s=0.1, c=lh_morph_sulc_sub)
    plt.title('Moved')
    ax = fig.add_subplot(144)
    ax.scatter(phi_reg.degree, theta_reg.degree, s=0.1, c=lh_morph_sulc_sub)
    plt.title('Moved FreeSurfer')
    plt.savefig(imagesavefilename)