"""
    Sust Global Climate Explorer API

     This API provides programmatic access to physical risk exposure data. For more guidance on using this API, please visit the Sust Global Dev Center: https://developers.sustglobal.com.   # noqa: E501

    The version of the OpenAPI document: beta
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sust.api.climate_explorer.clientgen
from sust.api.climate_explorer.clientgen.model.physical_risk_summary_indicators import PhysicalRiskSummaryIndicators


class TestPhysicalRiskSummaryIndicators(unittest.TestCase):
    """PhysicalRiskSummaryIndicators unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPhysicalRiskSummaryIndicators(self):
        """Test PhysicalRiskSummaryIndicators"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PhysicalRiskSummaryIndicators()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
