# Generated by Django 2.2.24 on 2021-08-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0052_auto_20210824_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementaction',
            name='result',
            field=models.CharField(choices=[('ST', 'Successfully treated'), ('UT', 'Unsuccessfully treated'), ('UN', 'Untreated'), ('UK', 'UK')], default='UK', max_length=3, verbose_name='Result'),
        ),
    ]
