# Generated by Django 3.1.4 on 2021-01-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_exam_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.CharField(default=0, max_length=4, verbose_name='Durasi Ujian'),
        ),
    ]
